OWNER_NAME="Kévøø😜"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "KEVOO-MD"
IMAGE_MENUMENU="https://telegra.ph/file/88ad273e040f262fe69ad.jpg"
NUMERO_OWNER= "255712682559"
OWNER_NAME= "Kévøø😜"
DATABASE_URL= ""
WARN_COUNT= "3"
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'

